Prevent PSBT::extract_tx from panicing
dongcarl/rust-bitcoin pull request #2
Opened 2018-11-06 16:05 UTC by stevenroose

2018-11-06 16:07 UTC, stevenroose commented
I think this is better than an extra Error variant because it's names `extract_tx`, which doesn't make claims on the finality of the tx.

2018-12-03 04:03 UTC, dongcarl requested changes

2018-12-03 04:03 UTC, dongcarl commented on src/util/psbt/mod.rs
> +            vin.script_sig = psbtin.final_script_sig.or_else(|| Some(Script::new())).unwrap();
```suggestion
            vin.script_sig = psbtin.final_script_sig.unwrap_or_else(|| Script::new());
```

2018-12-03 04:03 UTC, dongcarl commented on src/util/psbt/mod.rs
> +            vin.witness = psbtin.final_script_witness.or_else(|| Some(Vec::new())).unwrap();
```suggestion
            vin.witness = psbtin.final_script_witness.unwrap_or_else(|| Vec::new());
```

2018-12-03 17:02 UTC, stevenroose commented
Hehe, fine. Didn't know about those methods.

2018-12-03 18:48 UTC, dongcarl approved these changes

2018-12-03 18:49 UTC, merged